### ISSUE TITLE
Peer Review from Chloe Ouyang

### ISSUE THREAD

**Issue by chloeouyang** [ssetty767/Project#3]
Content: 1) the background color of the index page is too dark to see the words clearly. 2) The width of the paragraph is too large. Setting some blank margin on both the left side and right side may make it look better.
Technical: 1) delete the margin:0 and padding:0 in CSS style of ul in bowling page. 2) set vertical-align: top for the CSS style of td in bowling page.

**Comment by ssetty767** [comment]
Thanks for your feedback! will incorporate :)
